//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.TrupperReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ProductoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Producto[] ListaProductosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Producto[] ListaProductos {
            get {
                return this.ListaProductosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaProductosField, value) != true)) {
                    this.ListaProductosField = value;
                    this.RaisePropertyChanged("ListaProductos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/ML")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SKUField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((this.SKUField.Equals(value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/ML")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMaterno {
            get {
                return this.AMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AMaternoField, value) != true)) {
                    this.AMaternoField = value;
                    this.RaisePropertyChanged("AMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APaterno {
            get {
                return this.APaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.APaternoField, value) != true)) {
                    this.APaternoField = value;
                    this.RaisePropertyChanged("APaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ClienteResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Cliente[] ListaClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Cliente[] ListaClientes {
            get {
                return this.ListaClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaClientesField, value) != true)) {
                    this.ListaClientesField = value;
                    this.RaisePropertyChanged("ListaClientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/ML")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MontoPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PedidoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoPedido {
            get {
                return this.MontoPedidoField;
            }
            set {
                if ((this.MontoPedidoField.Equals(value) != true)) {
                    this.MontoPedidoField = value;
                    this.RaisePropertyChanged("MontoPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PedidoId {
            get {
                return this.PedidoIdField;
            }
            set {
                if ((this.PedidoIdField.Equals(value) != true)) {
                    this.PedidoIdField = value;
                    this.RaisePropertyChanged("PedidoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PedidoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Pedido[] ListaPedidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Pedido[] ListaPedidos {
            get {
                return this.ListaPedidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPedidosField, value) != true)) {
                    this.ListaPedidosField = value;
                    this.RaisePropertyChanged("ListaPedidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoDetalle", Namespace="http://schemas.datacontract.org/2004/07/ML")]
    [System.SerializableAttribute()]
    public partial class PedidoDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Pedido PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoDetalleResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PedidoDetalleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.PedidoDetalle[] ListaPedidoDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.PedidoDetalle[] ListaPedidoDetalle {
            get {
                return this.ListaPedidoDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPedidoDetalleField, value) != true)) {
                    this.ListaPedidoDetalleField = value;
                    this.RaisePropertyChanged("ListaPedidoDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaPedido", Namespace="http://schemas.datacontract.org/2004/07/ML.Entities")]
    [System.SerializableAttribute()]
    public partial class ConsultaPedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Pedido PedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.PedidoDetalle PedidoDetalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Pedido Pedido {
            get {
                return this.PedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoField, value) != true)) {
                    this.PedidoField = value;
                    this.RaisePropertyChanged("Pedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.PedidoDetalle PedidoDetalle {
            get {
                return this.PedidoDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.PedidoDetalleField, value) != true)) {
                    this.PedidoDetalleField = value;
                    this.RaisePropertyChanged("PedidoDetalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaPedidoResponse", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ConsultaPedidoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.Pedido[] ListaPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PL.TrupperReference.PedidoDetalle[] ListaPedidoDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.Pedido[] ListaPedido {
            get {
                return this.ListaPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPedidoField, value) != true)) {
                    this.ListaPedidoField = value;
                    this.RaisePropertyChanged("ListaPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PL.TrupperReference.PedidoDetalle[] ListaPedidoDetalle {
            get {
                return this.ListaPedidoDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaPedidoDetalleField, value) != true)) {
                    this.ListaPedidoDetalleField = value;
                    this.RaisePropertyChanged("ListaPedidoDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrupperReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductos", ReplyAction="http://tempuri.org/IService/GetProductosResponse")]
        PL.TrupperReference.ProductoResponse GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetProductos", ReplyAction="http://tempuri.org/IService/GetProductosResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.ProductoResponse> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCliente", ReplyAction="http://tempuri.org/IService/AddClienteResponse")]
        PL.TrupperReference.ClienteResponse AddCliente(PL.TrupperReference.Cliente cliente, PL.TrupperReference.Producto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddCliente", ReplyAction="http://tempuri.org/IService/AddClienteResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.ClienteResponse> AddClienteAsync(PL.TrupperReference.Cliente cliente, PL.TrupperReference.Producto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPedido", ReplyAction="http://tempuri.org/IService/AddPedidoResponse")]
        PL.TrupperReference.PedidoResponse AddPedido(int ClienteId, PL.TrupperReference.Pedido pedido, PL.TrupperReference.Producto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPedido", ReplyAction="http://tempuri.org/IService/AddPedidoResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.PedidoResponse> AddPedidoAsync(int ClienteId, PL.TrupperReference.Pedido pedido, PL.TrupperReference.Producto[] productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPedidoDetalle", ReplyAction="http://tempuri.org/IService/AddPedidoDetalleResponse")]
        PL.TrupperReference.PedidoDetalleResponse AddPedidoDetalle(int PedidoId, PL.TrupperReference.Producto producto, PL.TrupperReference.PedidoDetalle pedidoDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddPedidoDetalle", ReplyAction="http://tempuri.org/IService/AddPedidoDetalleResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.PedidoDetalleResponse> AddPedidoDetalleAsync(int PedidoId, PL.TrupperReference.Producto producto, PL.TrupperReference.PedidoDetalle pedidoDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPedidoById", ReplyAction="http://tempuri.org/IService/GetPedidoByIdResponse")]
        PL.TrupperReference.ConsultaPedidoResponse GetPedidoById(PL.TrupperReference.ConsultaPedido consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPedidoById", ReplyAction="http://tempuri.org/IService/GetPedidoByIdResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.ConsultaPedidoResponse> GetPedidoByIdAsync(PL.TrupperReference.ConsultaPedido consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePedidoById", ReplyAction="http://tempuri.org/IService/DeletePedidoByIdResponse")]
        PL.TrupperReference.PedidoResponse DeletePedidoById(PL.TrupperReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePedidoById", ReplyAction="http://tempuri.org/IService/DeletePedidoByIdResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.PedidoResponse> DeletePedidoByIdAsync(PL.TrupperReference.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePedidoDetalleById", ReplyAction="http://tempuri.org/IService/DeletePedidoDetalleByIdResponse")]
        PL.TrupperReference.PedidoDetalleResponse DeletePedidoDetalleById(PL.TrupperReference.PedidoDetalle pedidoDetalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DeletePedidoDetalleById", ReplyAction="http://tempuri.org/IService/DeletePedidoDetalleByIdResponse")]
        System.Threading.Tasks.Task<PL.TrupperReference.PedidoDetalleResponse> DeletePedidoDetalleByIdAsync(PL.TrupperReference.PedidoDetalle pedidoDetalle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : PL.TrupperReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<PL.TrupperReference.IService>, PL.TrupperReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PL.TrupperReference.ProductoResponse GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.ProductoResponse> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
        
        public PL.TrupperReference.ClienteResponse AddCliente(PL.TrupperReference.Cliente cliente, PL.TrupperReference.Producto[] productos) {
            return base.Channel.AddCliente(cliente, productos);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.ClienteResponse> AddClienteAsync(PL.TrupperReference.Cliente cliente, PL.TrupperReference.Producto[] productos) {
            return base.Channel.AddClienteAsync(cliente, productos);
        }
        
        public PL.TrupperReference.PedidoResponse AddPedido(int ClienteId, PL.TrupperReference.Pedido pedido, PL.TrupperReference.Producto[] productos) {
            return base.Channel.AddPedido(ClienteId, pedido, productos);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.PedidoResponse> AddPedidoAsync(int ClienteId, PL.TrupperReference.Pedido pedido, PL.TrupperReference.Producto[] productos) {
            return base.Channel.AddPedidoAsync(ClienteId, pedido, productos);
        }
        
        public PL.TrupperReference.PedidoDetalleResponse AddPedidoDetalle(int PedidoId, PL.TrupperReference.Producto producto, PL.TrupperReference.PedidoDetalle pedidoDetalle) {
            return base.Channel.AddPedidoDetalle(PedidoId, producto, pedidoDetalle);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.PedidoDetalleResponse> AddPedidoDetalleAsync(int PedidoId, PL.TrupperReference.Producto producto, PL.TrupperReference.PedidoDetalle pedidoDetalle) {
            return base.Channel.AddPedidoDetalleAsync(PedidoId, producto, pedidoDetalle);
        }
        
        public PL.TrupperReference.ConsultaPedidoResponse GetPedidoById(PL.TrupperReference.ConsultaPedido consulta) {
            return base.Channel.GetPedidoById(consulta);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.ConsultaPedidoResponse> GetPedidoByIdAsync(PL.TrupperReference.ConsultaPedido consulta) {
            return base.Channel.GetPedidoByIdAsync(consulta);
        }
        
        public PL.TrupperReference.PedidoResponse DeletePedidoById(PL.TrupperReference.Pedido pedido) {
            return base.Channel.DeletePedidoById(pedido);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.PedidoResponse> DeletePedidoByIdAsync(PL.TrupperReference.Pedido pedido) {
            return base.Channel.DeletePedidoByIdAsync(pedido);
        }
        
        public PL.TrupperReference.PedidoDetalleResponse DeletePedidoDetalleById(PL.TrupperReference.PedidoDetalle pedidoDetalle) {
            return base.Channel.DeletePedidoDetalleById(pedidoDetalle);
        }
        
        public System.Threading.Tasks.Task<PL.TrupperReference.PedidoDetalleResponse> DeletePedidoDetalleByIdAsync(PL.TrupperReference.PedidoDetalle pedidoDetalle) {
            return base.Channel.DeletePedidoDetalleByIdAsync(pedidoDetalle);
        }
    }
}
